### PR TITLE
Add doc examples for most `untrusted::Input` methods.

### PR DESCRIPTION
**Pull request by frewsxcv**
I agree to license my contributions to each file under the terms given
at the top of each file I changed.

### CODE REVIEW

**Comment by frewsxcv** [comment]
I like documentation when they include examples and [so does this RFC](https://github.com/steveklabnik/rfcs/blob/more-api-conventions/text/0000-more-api-documentation-conventions.md#examples-in-api-docs). @briansmith No feelings hurt if you feel otherwise. I couldn't think of a great example for `read_all_mut` and I'm a bit short on time so I didn't include one there. Let me know your thoughts and ideas for improvement.

**Comment by briansmith** [comment]
Thanks for this.

First, I think that your examples would be great to have as minimal unit tests. So, I suggest moving them to tests instead.

One of the problems that `untrusted::Input` tries to solve is DoS caused by panics. So, while I totally understand what you're trying to do here, I don't think that these code samples are actually good models for people to follow, because `assert!()` and `assert_eq!()` panic. Do you see what I mean here? (Sorry it's probably not very clear.)

So, instead, I think it would be better for the documentation to do similar stuff, but without using panicing stuff. e.g.

```rust
if a.is_empty() {
    return Err(());
}
```

Again, thanks for submitting this.

**Comment by frewsxcv** [comment]
Extracted out the examples into unit tests: https://github.com/briansmith/untrusted/pull/4

**Comment by frewsxcv** [comment]
I got rid of the panics. Not sure what you'll think of the changes. I'm pretty neutral.

**Comment by briansmith** [comment]
Sorry I never got around to looking at this. I'm just going to close this now to clear the backlog. I do think we should have some better documentation but I think we should refactor the API first.

**Comment by briansmith** [comment]
Also, thanks for the PR!

**Pull request closed without merging**
